### ISSUE TITLE
Picking up a large package you are pulling with your tail crashes the local server

### ISSUE THREAD

**Issue by Caketaco** [funky-station/funky-station#134]
## Description

As a reptilian, picking up a large package you are pulling with your tail causes the server to crash.

**Reproduction**

1. Spawn in as a reptilian species.
2. Spawn in a large package.
3. Pull it with your tail.
4. Pick up the large package. 

**Screenshots**

https://github.com/user-attachments/assets/3a024777-6b2e-40f0-b9f4-c05ac992f057

**Additional context**

<details>
<summary>Server console output on crash:</summary>
<br>

```ini
[FATL] unhandled: Robust.Shared.Utility.DebugAssertException: invalid metadata flags after events
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition, String message) in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\Utility\DebugTools.cs:line 196
   at Robust.Shared.Containers.SharedContainerSystem.Insert(Entity`3 toInsert, BaseContainer container, TransformComponent containerXform, Boolean force) in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\Containers\SharedContainerSystem.Insert.cs:line 128
   at Content.Shared.Hands.EntitySystems.SharedHandsSystem.DoPickup(EntityUid uid, Hand hand, EntityUid entity, HandsComponent hands, Boolean log) in D:\Desktop\funkystation\Content.Shared\Hands\EntitySystems\SharedHandsSystem.Pickup.cs:line 232
   at Content.Shared.Hands.EntitySystems.SharedHandsSystem.TryPickup(EntityUid uid, EntityUid entity, Hand hand, Boolean checkActionBlocker, Boolean animate, HandsComponent handsComp, ItemComponent item) in D:\Desktop\funkystation\Content.Shared\Hands\EntitySystems\SharedHandsSystem.Pickup.cs:line 122
   at Content.Shared.Hands.EntitySystems.SharedHandsSystem.TryPickup(EntityUid uid, EntityUid entity, String handName, Boolean checkActionBlocker, Boolean animateUser, Boolean animate, HandsComponent handsComp, ItemComponent item) in D:\Desktop\funkystation\Content.Shared\Hands\EntitySystems\SharedHandsSystem.Pickup.cs:line 61
   at Content.Shared.Item.SharedItemSystem.OnHandInteract(EntityUid uid, ItemComponent component, InteractHandEvent args) in D:\Desktop\funkystation\Content.Shared\Item\SharedItemSystem.cs:line 94
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass54_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 272
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass67_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 460
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass76_1.<EntCollectOrdered>b__0(Unit& ev) in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 664
   at Robust.Shared.GameObjects.EntityEventBus.DispatchOrderedEvents(Unit& eventArgs, ValueList`1& found) in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Ordering.cs:line 52
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalOrdered(EntityUid uid, Type eventType, EventData subs, Unit& unitRef, Boolean broadcast) in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Ordering.cs:line 43
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEventCore(EntityUid uid, Unit& unitRef, Type type, Boolean broadcast) in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 236
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 200
   at Robust.Shared.GameObjects.EntitySystem.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\GameObjects\EntitySystem.cs:line 159
   at Content.Shared.Interaction.SharedInteractionSystem.InteractHand(EntityUid user, EntityUid target) in D:\Desktop\funkystation\Content.Shared\Interaction\SharedInteractionSystem.cs:line 501
   at Content.Shared.Interaction.SharedInteractionSystem.UserInteraction(EntityUid user, EntityCoordinates coordinates, Nullable`1 target, Boolean altInteract, Boolean checkCanInteract, Boolean checkAccess, Boolean checkCanUse) in D:\Desktop\funkystation\Content.Shared\Interaction\SharedInteractionSystem.cs:line 428
   at Content.Shared.Interaction.SharedInteractionSystem.HandleUseInteraction(ICommonSession session, EntityCoordinates coords, EntityUid uid) in D:\Desktop\funkystation\Content.Shared\Interaction\SharedInteractionSystem.cs:line 315
   at Robust.Shared.Input.Binding.PointerInputCmdHandler.<>c__DisplayClass5_0.<.ctor>b__0(PointerInputCmdArgs& args) in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\Input\Binding\InputCmdHandler.cs:line 97
   at Robust.Shared.Input.Binding.PointerInputCmdHandler.HandleCmdMessage(IEntityManager entManager, ICommonSession session, IFullInputCmdMessage message) in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\Input\Binding\InputCmdHandler.cs:line 127
   at Robust.Server.GameObjects.InputSystem.InputMessageHandler(InputCmdMessage message, EntitySessionEventArgs eventArgs) in D:\Desktop\funkystation\RobustToolbox\Robust.Server\GameObjects\EntitySystems\InputSystem.cs:line 65
   at Robust.Shared.GameObjects.EventBusExt.HandlerWrapper`1.Invoke(EntitySessionMessage`1 msg) in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\GameObjects\EventBusExt.cs:line 46
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass4_0`1.<SubscribeEvent>b__0(Unit& ev) in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 173
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs) in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 335
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Unit& unitRef, Type eventType) in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 324
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent(EventSource source, Object toRaise) in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 267
   at Robust.Server.GameObjects.ServerEntityManager.<Initialize>b__8_0(Object _, Object systemMsg) in D:\Desktop\funkystation\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 53
   at Robust.Server.GameObjects.ServerEntityManager.DispatchEntityNetworkMessage(MsgEntity message) in D:\Desktop\funkystation\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 266
   at Robust.Server.GameObjects.ServerEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in D:\Desktop\funkystation\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 192
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in D:\Desktop\funkystation\RobustToolbox\Robust.Server\BaseServer.cs:line 731
   at Robust.Server.BaseServer.<SetupMainLoop>b__67_1(Object sender, FrameEventArgs args) in D:\Desktop\funkystation\RobustToolbox\Robust.Server\BaseServer.cs:line 544
   at Robust.Shared.Timing.GameLoop.Run() in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 235
   at Robust.Server.BaseServer.MainLoop() in D:\Desktop\funkystation\RobustToolbox\Robust.Server\BaseServer.cs:line 571
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in D:\Desktop\funkystation\RobustToolbox\Robust.Server\Program.cs:line 74
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in D:\Desktop\funkystation\RobustToolbox\Robust.Server\Program.cs:line 42
   at Robust.Server.ContentStart.Start(String[] args) in D:\Desktop\funkystation\RobustToolbox\Robust.Server\ContentStart.cs:line 10
   at Content.Server.Program.Main(String[] args) in D:\Desktop\funkystation\Content.Server\Program.cs:line 9
Unhandled exception. Robust.Shared.Utility.DebugAssertException: invalid metadata flags after events
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition, String message) in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\Utility\DebugTools.cs:line 196
   at Robust.Shared.Containers.SharedContainerSystem.Insert(Entity`3 toInsert, BaseContainer container, TransformComponent containerXform, Boolean force) in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\Containers\SharedContainerSystem.Insert.cs:line 128
   at Content.Shared.Hands.EntitySystems.SharedHandsSystem.DoPickup(EntityUid uid, Hand hand, EntityUid entity, HandsComponent hands, Boolean log) in D:\Desktop\funkystation\Content.Shared\Hands\EntitySystems\SharedHandsSystem.Pickup.cs:line 232
   at Content.Shared.Hands.EntitySystems.SharedHandsSystem.TryPickup(EntityUid uid, EntityUid entity, Hand hand, Boolean checkActionBlocker, Boolean animate, HandsComponent handsComp, ItemComponent item) in D:\Desktop\funkystation\Content.Shared\Hands\EntitySystems\SharedHandsSystem.Pickup.cs:line 122
   at Content.Shared.Hands.EntitySystems.SharedHandsSystem.TryPickup(EntityUid uid, EntityUid entity, String handName, Boolean checkActionBlocker, Boolean animateUser, Boolean animate, HandsComponent handsComp, ItemComponent item) in D:\Desktop\funkystation\Content.Shared\Hands\EntitySystems\SharedHandsSystem.Pickup.cs:line 61
   at Content.Shared.Item.SharedItemSystem.OnHandInteract(EntityUid uid, ItemComponent component, InteractHandEvent args) in D:\Desktop\funkystation\Content.Shared\Item\SharedItemSystem.cs:line 94
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass54_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 272
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass67_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 460
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass76_1.<EntCollectOrdered>b__0(Unit& ev) in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 664
   at Robust.Shared.GameObjects.EntityEventBus.DispatchOrderedEvents(Unit& eventArgs, ValueList`1& found) in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Ordering.cs:line 52
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalOrdered(EntityUid uid, Type eventType, EventData subs, Unit& unitRef, Boolean broadcast) in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Ordering.cs:line 43
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEventCore(EntityUid uid, Unit& unitRef, Type type, Boolean broadcast) in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 236
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 200
   at Robust.Shared.GameObjects.EntitySystem.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\GameObjects\EntitySystem.cs:line 159
   at Content.Shared.Interaction.SharedInteractionSystem.InteractHand(EntityUid user, EntityUid target) in D:\Desktop\funkystation\Content.Shared\Interaction\SharedInteractionSystem.cs:line 501
   at Content.Shared.Interaction.SharedInteractionSystem.UserInteraction(EntityUid user, EntityCoordinates coordinates, Nullable`1 target, Boolean altInteract, Boolean checkCanInteract, Boolean checkAccess, Boolean checkCanUse) in D:\Desktop\funkystation\Content.Shared\Interaction\SharedInteractionSystem.cs:line 428
   at Content.Shared.Interaction.SharedInteractionSystem.HandleUseInteraction(ICommonSession session, EntityCoordinates coords, EntityUid uid) in D:\Desktop\funkystation\Content.Shared\Interaction\SharedInteractionSystem.cs:line 315
   at Robust.Shared.Input.Binding.PointerInputCmdHandler.<>c__DisplayClass5_0.<.ctor>b__0(PointerInputCmdArgs& args) in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\Input\Binding\InputCmdHandler.cs:line 97
   at Robust.Shared.Input.Binding.PointerInputCmdHandler.HandleCmdMessage(IEntityManager entManager, ICommonSession session, IFullInputCmdMessage message) in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\Input\Binding\InputCmdHandler.cs:line 127
   at Robust.Server.GameObjects.InputSystem.InputMessageHandler(InputCmdMessage message, EntitySessionEventArgs eventArgs) in D:\Desktop\funkystation\RobustToolbox\Robust.Server\GameObjects\EntitySystems\InputSystem.cs:line 65
   at Robust.Shared.GameObjects.EventBusExt.HandlerWrapper`1.Invoke(EntitySessionMessage`1 msg) in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\GameObjects\EventBusExt.cs:line 46
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass4_0`1.<SubscribeEvent>b__0(Unit& ev) in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 173
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs) in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 335
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Unit& unitRef, Type eventType) in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 324
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent(EventSource source, Object toRaise) in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 267
   at Robust.Server.GameObjects.ServerEntityManager.<Initialize>b__8_0(Object _, Object systemMsg) in D:\Desktop\funkystation\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 53
   at Robust.Server.GameObjects.ServerEntityManager.DispatchEntityNetworkMessage(MsgEntity message) in D:\Desktop\funkystation\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 266
   at Robust.Server.GameObjects.ServerEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in D:\Desktop\funkystation\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 192
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in D:\Desktop\funkystation\RobustToolbox\Robust.Server\BaseServer.cs:line 731
   at Robust.Server.BaseServer.<SetupMainLoop>b__67_1(Object sender, FrameEventArgs args) in D:\Desktop\funkystation\RobustToolbox\Robust.Server\BaseServer.cs:line 544
   at Robust.Shared.Timing.GameLoop.Run() in D:\Desktop\funkystation\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 235
   at Robust.Server.BaseServer.MainLoop() in D:\Desktop\funkystation\RobustToolbox\Robust.Server\BaseServer.cs:line 571
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in D:\Desktop\funkystation\RobustToolbox\Robust.Server\Program.cs:line 74
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in D:\Desktop\funkystation\RobustToolbox\Robust.Server\Program.cs:line 42
   at Robust.Server.ContentStart.Start(String[] args) in D:\Desktop\funkystation\RobustToolbox\Robust.Server\ContentStart.cs:line 10
   at Content.Server.Program.Main(String[] args) in D:\Desktop\funkystation\Content.Server\Program.cs:line 9
[DEBG] db.op: Successfully saved 1 admin logs.
Press any key to continue . . .
```
</details>

**Comment by taydeo** [comment]
Thanks for the info
